package com.example.a12306test.station_pack;

import com.example.a12306test.bean.CityBean;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by 昭阳 on 2019/4/16.
 */
public class Station_Util {
    public String station = "北京北 VAP\n" +
            "北京东 BOP\n" +
            "北京 BJP\n" +
            "北京南 VNP\n" +
            "北京西 BXP\n" +
            "广州南 IZQ\n" +
            "重庆北 CUW\n" +
            "重庆 CQW\n" +
            "重庆南 CRW\n" +
            "广州东 GGQ\n" +
            "上海 SHH\n" +
            "上海南 SNH\n" +
            "上海虹桥 AOH\n" +
            "上海西 SXH\n" +
            "天津北 TBP\n" +
            "天津 TJP\n" +
            "天津南 TIP\n" +
            "天津西 TXP\n" +
            "长春 CCT\n" +
            "长春南 CET\n" +
            "长春西 CRT\n" +
            "成都东 ICW\n" +
            "成都南 CNW\n" +
            "成都 CDW\n" +
            "长沙 CSQ\n" +
            "长沙南 CWQ\n" +
            "福州 FZS\n" +
            "福州南 FYS\n" +
            "贵阳 GIW\n" +
            "广州 GZQ\n" +
            "广州西 GXQ\n" +
            "哈尔滨 HBB\n" +
            "哈尔滨东 VBB\n" +
            "哈尔滨西 VAB\n" +
            "合肥 HFH\n" +
            "合肥西 HTH\n" +
            "呼和浩特东 NDC\n" +
            "呼和浩特 HHC\n" +
            "海口东 HMQ\n" +
            "海口 VUQ\n" +
            "杭州东 HGH\n" +
            "杭州 HZH\n" +
            "杭州南 XHH\n" +
            "济南 JNK\n" +
            "济南东 JAK\n" +
            "济南西 JGK\n" +
            "昆明 KMM\n" +
            "昆明西 KXM\n" +
            "拉萨 LSO\n" +
            "兰州东 LVJ\n" +
            "兰州 LZJ\n" +
            "兰州西 LAJ\n" +
            "南昌 NCG\n" +
            "南京 NJH\n" +
            "南京南 NKH\n" +
            "南宁 NNZ\n" +
            "石家庄北 VVP\n" +
            "石家庄 SJP\n" +
            "沈阳 SYT\n" +
            "沈阳北 SBT\n" +
            "沈阳东 SDT\n" +
            "太原北 TBV\n" +
            "太原东 TDV\n" +
            "太原 TYV\n" +
            "武汉 WHN\n" +
            "王家营西 KNM\n" +
            "乌鲁木齐南 WMR\n" +
            "西安北 EAY\n" +
            "西安 XAY\n" +
            "西安南 CAY\n" +
            "西宁 XNO\n" +
            "银川 YIJ\n" +
            "郑州 ZZF\n" +
            "阿尔山 ART\n" +
            "安康 AKY\n" +
            "阿克苏 ASR\n" +
            "阿里河 AHX\n" +
            "阿拉山口 AKR\n" +
            "安平 APT\n" +
            "安庆 AQH\n" +
            "安顺 ASW\n" +
            "鞍山 AST\n" +
            "安阳 AYF\n" +
            "北安 BAB\n" +
            "蚌埠 BBH\n" +
            "白城 BCT\n" +
            "北海 BHZ\n" +
            "白河 BEL\n" +
            "白涧 BAP\n" +
            "宝鸡 BJY\n" +
            "滨江 BJB\n" +
            "博克图 BKX\n" +
            "百色 BIZ\n" +
            "白山市 HJL\n" +
            "北台 BTT\n" +
            "包头东 BDC\n" +
            "包头 BTC\n" +
            "北屯市 BXR\n" +
            "本溪 BXT\n" +
            "白云鄂博 BEC\n" +
            "白银西 BXJ\n" +
            "亳州 BZH\n" +
            "赤壁 CBN\n" +
            "常德 VGQ\n" +
            "承德 CDP\n" +
            "长甸 CDT\n" +
            "赤峰 CFD\n" +
            "茶陵 CDG\n" +
            "苍南 CEH\n" +
            "昌平 CPP\n" +
            "崇仁 CRG\n" +
            "昌图 CTT\n" +
            "长汀镇 CDB\n" +
            "曹县 CXK\n" +
            "楚雄 COM\n" +
            "陈相屯 CXT\n" +
            "长治北 CBF\n" +
            "长征 CZJ\n" +
            "池州 IYH\n" +
            "常州 CZH\n" +
            "郴州 CZQ\n" +
            "长治 CZF\n" +
            "沧州 COP\n" +
            "崇左 CZZ\n" +
            "大安北 RNT\n" +
            "大成 DCT\n" +
            "丹东 DUT\n" +
            "东方红 DFB\n" +
            "东莞东 DMQ\n" +
            "大虎山 DHD\n" +
            "敦煌 DHJ\n" +
            "敦化 DHL\n" +
            "德惠 DHT\n" +
            "东京城 DJB\n" +
            "大涧 DFP\n" +
            "都江堰 DDW\n" +
            "大连北 DFT\n" +
            "大理 DKM\n" +
            "大连 DLT\n" +
            "定南 DNG\n" +
            "大庆 DZX\n" +
            "东胜 DOC\n" +
            "大石桥 DQT\n" +
            "大同 DTV\n" +
            "东营 DPK\n" +
            "大杨树 DUX\n" +
            "都匀 RYW\n" +
            "邓州 DOF\n" +
            "达州 RXW\n" +
            "德州 DZP\n" +
            "额济纳 EJC\n" +
            "二连 RLC\n" +
            "恩施 ESN\n" +
            "福鼎 FES\n" +
            "风陵渡 FLV\n" +
            "涪陵 FLW\n" +
            "富拉尔基 FRX\n" +
            "抚顺北 FET\n" +
            "佛山 FSQ\n" +
            "阜新 FXD\n" +
            "阜阳 FYH\n" +
            "格尔木 GRO\n" +
            "广汉 GHW\n" +
            "古交 GJV\n" +
            "桂林北 GBZ\n" +
            "古莲 GRX\n" +
            "桂林 GLZ\n" +
            "固始 GXN\n" +
            "广水 GSN\n" +
            "干塘 GNJ\n" +
            "广元 GYW\n" +
            "广州北 GBQ\n" +
            "赣州 GZG\n" +
            "公主岭 GLT\n" +
            "公主岭南 GBT\n" +
            "淮安 AUH\n" +
            "鹤北 HMB\n" +
            "淮北 HRH\n" +
            "淮滨 HVN\n" +
            "河边 HBV\n" +
            "潢川 KCN\n" +
            "韩城 HCY\n" +
            "邯郸 HDP\n" +
            "横道河子 HDB\n" +
            "鹤岗 HGB\n" +
            "皇姑屯 HTT\n" +
            "红果 HEM\n" +
            "黑河 HJB\n" +
            "怀化 HHQ\n" +
            "汉口 HKN\n" +
            "葫芦岛 HLD\n" +
            "海拉尔 HRX\n" +
            "霍林郭勒 HWD\n" +
            "海伦 HLB\n" +
            "侯马 HMV\n" +
            "哈密 HMR\n" +
            "淮南 HAH\n" +
            "桦南 HNB\n" +
            "海宁西 EUH\n" +
            "鹤庆 HQM\n" +
            "怀柔北 HBP\n" +
            "怀柔 HRP\n" +
            "黄石东 OSN\n" +
            "华山 HSY\n" +
            "黄石 HSN\n" +
            "黄山 HKH\n" +
            "衡水 HSP\n" +
            "衡阳 HYQ\n" +
            "菏泽 HIK\n" +
            "贺州 HXZ\n" +
            "汉中 HOY\n" +
            "惠州 HCQ\n" +
            "吉安 VAG\n" +
            "集安 JAL\n" +
            "江边村 JBG\n" +
            "晋城 JCF\n" +
            "金城江 JJZ\n" +
            "景德镇 JCG\n" +
            "嘉峰 JFF\n" +
            "加格达奇 JGX\n" +
            "井冈山 JGG\n" +
            "蛟河 JHL\n" +
            "金华南 RNH\n" +
            "金华 JBH\n" +
            "九江 JJG\n" +
            "吉林 JLL\n" +
            "荆门 JMN\n" +
            "佳木斯 JMB\n" +
            "济宁 JIK\n" +
            "集宁南 JAC\n" +
            "酒泉 JQJ\n" +
            "江山 JUH\n" +
            "吉首 JIQ\n" +
            "九台 JTL\n" +
            "镜铁山 JVJ\n" +
            "鸡西 JXB\n" +
            "蓟县 JKP\n" +
            "绩溪县 JRH\n" +
            "嘉峪关 JGJ\n" +
            "江油 JFW\n" +
            "锦州 JZD\n" +
            "金州 JZT\n" +
            "库尔勒 KLR\n" +
            "开封 KFF\n" +
            "岢岚 KLV\n" +
            "凯里 KLW\n" +
            "喀什 KSR\n" +
            "昆山南 KNH\n" +
            "奎屯 KTR\n" +
            "开原 KYT\n" +
            "六安 UAH\n" +
            "灵宝 LBF\n" +
            "芦潮港 UCH\n" +
            "隆昌 LCW\n" +
            "陆川 LKZ\n" +
            "利川 LCN\n" +
            "临川 LCG\n" +
            "潞城 UTP\n" +
            "鹿道 LDL\n" +
            "娄底 LDQ\n" +
            "临汾 LFV\n" +
            "良各庄 LGP\n" +
            "临河 LHC\n" +
            "漯河 LON\n" +
            "绿化 LWJ\n" +
            "隆化 UHP\n" +
            "丽江 LHM\n" +
            "临江 LQL\n" +
            "龙井 LJL\n" +
            "吕梁 LHV\n" +
            "醴陵 LLG\n" +
            "柳林南 LKV\n" +
            "滦平 UPP\n" +
            "六盘水 UMW\n" +
            "灵丘 LVV\n" +
            "旅顺 LST\n" +
            "陇西 LXJ\n" +
            "澧县 LEQ\n" +
            "兰溪 LWH\n" +
            "临西 UEP\n" +
            "龙岩 LYS\n" +
            "耒阳 LYQ\n" +
            "洛阳 LYF\n" +
            "洛阳东 LDF\n" +
            "连云港东 UKH\n" +
            "临沂 LVK\n" +
            "洛阳龙门 LLF\n" +
            "柳园 DHR\n" +
            "凌源 LYD\n" +
            "辽源 LYL\n" +
            "立志 LZX\n" +
            "柳州 LZZ\n" +
            "辽中 LZD\n" +
            "麻城 MCN\n" +
            "免渡河 MDX\n" +
            "牡丹江 MDB\n" +
            "莫尔道嘎 MRX\n" +
            "满归 MHX\n" +
            "明光 MGH\n" +
            "漠河 MVX\n" +
            "茂名东 MDQ\n" +
            "茂名 MMZ\n" +
            "密山 MSB\n" +
            "马三家 MJT\n" +
            "麻尾 VAW\n" +
            "绵阳 MYW\n" +
            "梅州 MOQ\n" +
            "满洲里 MLX\n" +
            "宁波东 NVH\n" +
            "宁波 NGH\n" +
            "南岔 NCB\n" +
            "南充 NCW\n" +
            "南丹 NDZ\n" +
            "南大庙 NMP\n" +
            "南芬 NFT\n" +
            "讷河 NHX\n" +
            "嫩江 NGX\n" +
            "内江 NJW\n" +
            "南平 NPS\n" +
            "南通 NUH\n" +
            "南阳 NFF\n" +
            "碾子山 NZX\n" +
            "平顶山 PEN\n" +
            "盘锦 PVD\n" +
            "平凉 PIJ\n" +
            "平凉南 POJ\n" +
            "平泉 PQP\n" +
            "坪石 PSQ\n" +
            "萍乡 PXG\n" +
            "凭祥 PXZ\n" +
            "郫县西 PCW\n" +
            "攀枝花 PRW\n" +
            "蕲春 QRN\n" +
            "青城山 QSW\n" +
            "青岛 QDK\n" +
            "清河城 QYP\n" +
            "黔江 QNW\n" +
            "曲靖 QJM\n" +
            "前进镇 QEB\n" +
            "齐齐哈尔 QHX\n" +
            "七台河 QTB\n" +
            "沁县 QVV\n" +
            "泉州东 QRS\n" +
            "泉州 QYS\n" +
            "衢州 QEH\n" +
            "融安 RAZ\n" +
            "汝箕沟 RQJ\n" +
            "瑞金 RJG\n" +
            "日照 RZK\n" +
            "双城堡 SCB\n" +
            "绥芬河 SFB\n" +
            "韶关东 SGQ\n" +
            "山海关 SHD\n" +
            "绥化 SHB\n" +
            "三间房 SFX\n" +
            "苏家屯 SXT\n" +
            "舒兰 SLL\n" +
            "三明 SMS\n" +
            "神木 OMY\n" +
            "三门峡 SMF\n" +
            "商南 ONY\n" +
            "遂宁 NIW\n" +
            "四平 SPT\n" +
            "商丘 SQF\n" +
            "上饶 SRG\n" +
            "韶山 SSQ\n" +
            "宿松 OAH\n" +
            "汕头 OTQ\n" +
            "邵武 SWS\n" +
            "涉县 OEP\n" +
            "三亚 SEQ\n" +
            "邵阳 SYQ\n" +
            "十堰 SNN\n" +
            "双鸭山 SSB\n" +
            "松原 VYT\n" +
            "深圳 SZQ\n" +
            "苏州 SZH\n" +
            "随州 SZN\n" +
            "宿州 OXH\n" +
            "朔州 SUV\n" +
            "深圳西 OSQ\n" +
            "塘豹 TBQ\n" +
            "塔尔气 TVX\n" +
            "潼关 TGY\n" +
            "塘沽 TGP\n" +
            "塔河 TXX\n" +
            "通化 THL\n" +
            "泰来 TLX\n" +
            "吐鲁番 TFR\n" +
            "通辽 TLD\n" +
            "铁岭 TLT\n" +
            "陶赖昭 TPT\n" +
            "图们 TML\n" +
            "铜仁 RDQ\n" +
            "唐山北 FUP\n" +
            "田师府 TFT\n" +
            "泰山 TAK\n" +
            "唐山 TSP\n" +
            "天水 TSJ\n" +
            "通远堡 TYT\n" +
            "太阳升 TQT\n" +
            "泰州 UTH\n" +
            "桐梓 TZW\n" +
            "通州西 TAP\n" +
            "五常 WCB\n" +
            "武昌 WCN\n" +
            "瓦房店 WDT\n" +
            "威海 WKK\n" +
            "芜湖 WHH\n" +
            "乌海西 WXC\n" +
            "吴家屯 WJT\n" +
            "武隆 WLW\n" +
            "乌兰浩特 WWT\n" +
            "渭南 WNY\n" +
            "威舍 WSM\n" +
            "歪头山 WIT\n" +
            "武威 WUJ\n" +
            "武威南 WWJ\n" +
            "无锡 WXH\n" +
            "乌西 WXR\n" +
            "乌伊岭 WPB\n" +
            "武夷山 WAS\n" +
            "万源 WYY\n" +
            "万州 WYW\n" +
            "梧州 WZZ\n" +
            "温州 RZH\n" +
            "温州南 VRH\n" +
            "西昌 ECW\n" +
            "许昌 XCF\n" +
            "西昌南 ENW\n" +
            "香坊 XFB\n" +
            "轩岗 XGV\n" +
            "兴国 EUG\n" +
            "宣汉 XHY\n" +
            "新会 EFQ\n" +
            "新晃 XLQ\n" +
            "锡林浩特 XTC\n" +
            "兴隆县 EXP\n" +
            "厦门北 XKS\n" +
            "厦门 XMS\n" +
            "厦门高崎 XBS\n" +
            "秀山 ETW\n" +
            "小市 XST\n" +
            "向塘 XTG\n" +
            "宣威 XWM\n" +
            "新乡 XXF\n" +
            "信阳 XUN\n" +
            "咸阳 XYY\n" +
            "襄阳 XFN\n" +
            "熊岳城 XYT\n" +
            "兴义 XRZ\n" +
            "新沂 VIH\n" +
            "新余 XUG\n" +
            "徐州 XCH\n" +
            "延安 YWY\n" +
            "宜宾 YBW\n" +
            "亚布力南 YWB\n" +
            "叶柏寿 YBD\n" +
            "宜昌东 HAN\n" +
            "永川 YCW\n" +
            "宜昌 YCN\n" +
            "盐城 AFH\n" +
            "运城 YNV\n" +
            "伊春 YCB\n" +
            "榆次 YCV\n" +
            "杨村 YBP\n" +
            "宜春西 YCG\n" +
            "伊尔施 YET\n" +
            "燕岗 YGW\n" +
            "永济 YIV\n" +
            "延吉 YJL\n" +
            "营口 YKT\n" +
            "牙克石 YKX\n" +
            "阎良 YNY\n" +
            "玉林 YLZ\n" +
            "榆林 ALY\n" +
            "一面坡 YPB\n" +
            "伊宁 YMR\n" +
            "阳平关 YAY\n" +
            "玉屏 YZW\n" +
            "原平 YPV\n" +
            "延庆 YNP\n" +
            "阳泉曲 YYV\n" +
            "玉泉 YQB\n" +
            "阳泉 AQP\n" +
            "玉山 YNG\n" +
            "营山 NUW\n" +
            "燕山 AOP\n" +
            "榆树 YRT\n" +
            "鹰潭 YTG\n" +
            "烟台 YAK\n" +
            "伊图里河 YEX\n" +
            "玉田县 ATP\n" +
            "义乌 YWH\n" +
            "阳新 YON\n" +
            "义县 YXD\n" +
            "益阳 AEQ\n" +
            "岳阳 YYQ\n" +
            "永州 AOQ\n" +
            "扬州 YLH\n" +
            "淄博 ZBK\n" +
            "镇城底 ZDV\n" +
            "自贡 ZGW\n" +
            "珠海 ZHQ\n" +
            "珠海北 ZIQ\n" +
            "湛江 ZJZ\n" +
            "镇江 ZJH\n" +
            "张家界 DIQ\n" +
            "张家口 ZKP\n" +
            "张家口南 ZMP\n" +
            "周口 ZKN\n" +
            "哲里木 ZLC\n" +
            "扎兰屯 ZTX\n" +
            "驻马店 ZDN\n" +
            "肇庆 ZVQ\n" +
            "周水子 ZIT\n" +
            "昭通 ZDW\n" +
            "中卫 ZWJ\n" +
            "资阳 ZYW\n" +
            "遵义 ZIW\n" +
            "枣庄 ZEK\n" +
            "资中 ZZW\n" +
            "株洲 ZZQ\n" +
            "枣庄西 ZFK\n" +
            "昂昂溪 AAX\n" +
            "阿城 ACB\n" +
            "安达 ADX\n" +
            "安德 ARW\n" +
            "安定 ADP\n" +
            "安广 AGT\n" +
            "艾河 AHP\n" +
            "安化 PKQ\n" +
            "艾家村 AJJ\n" +
            "鳌江 ARH\n" +
            "安家 AJB\n" +
            "阿金 AJD\n" +
            "阿克陶 AER\n" +
            "安口窑 AYY\n" +
            "敖力布告 ALD\n" +
            "安龙 AUZ\n" +
            "阿龙山 ASX\n" +
            "安陆 ALN\n" +
            "阿木尔 JTX\n" +
            "阿南庄 AZM\n" +
            "安庆西 APH\n" +
            "鞍山西 AXT\n" +
            "安塘 ATV\n" +
            "安亭北 ASH\n" +
            "阿图什 ATR\n" +
            "安图 ATL\n" +
            "安溪 AXS\n" +
            "博鳌 BWQ\n" +
            "北碚 BPW\n" +
            "白壁关 BGV\n" +
            "蚌埠南 BMH\n" +
            "巴楚 BCR\n" +
            "板城 BUP\n" +
            "北戴河 BEP\n" +
            "保定 BDP\n" +
            "宝坻 BPP\n" +
            "八达岭 ILP\n" +
            "巴东 BNN\n" +
            "柏果 BGM\n" +
            "布海 BUT\n" +
            "白河东 BIY\n" +
            "贲红 BVC\n" +
            "宝华山 BWH\n" +
            "白河县 BEY\n" +
            "白芨沟 BJJ\n" +
            "碧鸡关 BJM\n" +
            "北滘 IBQ\n" +
            "碧江 BLQ\n" +
            "白鸡坡 BBM\n" +
            "笔架山 BSB\n" +
            "八角台 BTD\n" +
            "保康 BKD\n" +
            "白奎堡 BKB\n" +
            "白狼 BAT\n" +
            "百浪 BRZ\n" +
            "博乐 BOR\n" +
            "宝拉格 BQC\n" +
            "巴林 BLX\n" +
            "宝林 BNB\n" +
            "北流 BOZ\n" +
            "勃利 BLB\n" +
            "布列开 BLR\n" +
            "宝龙山 BND\n" +
            "百里峡 AAP\n" +
            "八面城 BMD\n" +
            "班猫箐 BNM\n" +
            "八面通 BMB\n" +
            "北马圈子 BRP\n" +
            "北票南 RPD\n" +
            "白旗 BQP\n" +
            "宝泉岭 BQB\n" +
            "白泉 BQL\n" +
            "白沙 BSW\n" +
            "巴山 BAY\n" +
            "白水江 BSY\n" +
            "白沙坡 BPM\n" +
            "白石山 BAL\n" +
            "白水镇 BUM\n" +
            "坂田 BTQ\n" +
            "泊头 BZP\n" +
            "北屯 BYP\n" +
            "本溪湖 BHT\n" +
            "博兴 BXK\n" +
            "八仙筒 VXD\n" +
            "白音察干 BYC\n" +
            "背荫河 BYB\n" +
            "北营 BIV\n" +
            "巴彦高勒 BAC\n" +
            "白音他拉 BID\n" +
            "鲅鱼圈 BYT\n" +
            "白银市 BNJ\n" +
            "白音胡硕 BCD\n" +
            "巴中 IEW\n" +
            "霸州 RMP\n" +
            "北宅 BVP\n" +
            "赤壁北 CIN\n" +
            "查布嘎 CBC\n" +
            "长城 CEJ\n" +
            "长冲 CCM\n" +
            "承德东 CCP\n" +
            "赤峰西 CID\n" +
            "嵯岗 CAX\n" +
            "柴岗 CGT\n" +
            "长葛 CEF\n" +
            "柴沟堡 CGV\n" +
            "城固 CGY\n" +
            "陈官营 CAJ\n" +
            "成高子 CZB\n" +
            "草海 WBW\n" +
            "柴河 CHB\n" +
            "册亨 CHZ\n" +
            "草河口 CKT\n" +
            "崔黄口 CHP\n" +
            "巢湖 CIH\n" +
            "蔡家沟 CJT\n" +
            "成吉思汗 CJX\n" +
            "岔江 CAM\n" +
            "蔡家坡 CJY\n" +
            "昌乐 CLK\n" +
            "超梁沟 CYP\n" +
            "慈利 CUQ\n" +
            "昌黎 CLP\n" +
            "长岭子 CLT\n" +
            "晨明 CMB\n" +
            "长农 CNJ\n" +
            "昌平北 VBP\n" +
            "常平 DAQ\n" +
            "长坡岭 CPM\n" +
            "辰清 CQB\n" +
            "楚山 CSB\n" +
            "长寿 EFW\n" +
            "磁山 CSP\n" +
            "苍石 CST\n" +
            "草市 CSL\n" +
            "察素齐 CSC\n" +
            "长山屯 CVT\n" +
            "长汀 CES\n" +
            "昌图西 CPT\n" +
            "春湾 CQQ\n" +
            "磁县 CIP\n" +
            "岑溪 CNZ\n" +
            "辰溪 CXQ\n" +
            "磁西 CRP\n" +
            "长兴南 CFH\n" +
            "磁窑 CYK\n" +
            "朝阳 CYD\n" +
            "春阳 CAL\n" +
            "城阳 CEK\n" +
            "创业村 CEX\n" +
            "朝阳川 CYL\n" +
            "朝阳地 CDD\n" +
            "长垣 CYF\n" +
            "朝阳镇 CZL\n" +
            "滁州北 CUH\n" +
            "常州北 ESH\n" +
            "滁州 CXH\n" +
            "潮州 CKQ\n" +
            "常庄 CVK\n" +
            "曹子里 CFP\n" +
            "车转湾 CWM\n" +
            "郴州西 ICQ\n" +
            "沧州西 CBP\n" +
            "德安 DAG\n" +
            "大安 RAT\n" +
            "大坝 DBJ\n" +
            "大板 DBC\n" +
            "大巴 DBD\n" +
            "到保 RBT\n" +
            "定边 DYJ\n" +
            "东边井 DBB\n" +
            "德伯斯 RDT\n" +
            "打柴沟 DGJ\n" +
            "德昌 DVW\n" +
            "滴道 DDB\n" +
            "大磴沟 DKJ\n" +
            "刀尔登 DRD\n" +
            "得耳布尔 DRX\n" +
            "东方 UFQ\n" +
            "丹凤 DGY\n" +
            "东丰 DIL\n" +
            "都格 DMM\n" +
            "大官屯 DTT\n" +
            "大关 RGW\n" +
            "东光 DGP\n" +
            "东海 DHB\n" +
            "大灰厂 DHP\n" +
            "大红旗 DQD\n" +
            "东海县 DQH\n" +
            "德惠西 DXT\n" +
            "达家沟 DJT\n" +
            "东津 DKB\n" +
            "杜家 DJL\n" +
            "大口屯 DKP\n" +
            "东来 RVD\n" +
            "德令哈 DHO\n" +
            "大陆号 DLC\n" +
            "带岭 DLB\n" +
            "大林 DLD\n" +
            "达拉特旗 DIC\n" +
            "独立屯 DTX\n" +
            "豆罗 DLV\n" +
            "达拉特西 DNC\n" +
            "东明村 DMD\n" +
            "洞庙河 DEP\n" +
            "东明县 DNF\n" +
            "大拟 DNZ\n" +
            "大平房 DPD\n" +
            "大盘石 RPP\n" +
            "大埔 DPI\n" +
            "大堡 DVT\n" +
            "大庆东 LFX\n" +
            "大其拉哈 DQX\n" +
            "道清 DML\n" +
            "对青山 DQB\n" +
            "德清西 MOH\n" +
            "大庆西 RHX\n" +
            "东升 DRQ\n" +
            "独山 RWW\n" +
            "砀山 DKH\n" +
            "登沙河 DWT\n" +
            "读书铺 DPM\n" +
            "大石头 DSL\n" +
            "东胜西 DYC\n" +
            "大石寨 RZT\n" +
            "东台 DBH\n" +
            "定陶 DQK\n" +
            "灯塔 DGT\n" +
            "大田边 DBM\n" +
            "东通化 DTL\n" +
            "丹徒 RUH\n" +
            "大屯 DNT\n" +
            "东湾 DRJ\n" +
            "大武口 DFJ\n" +
            "低窝铺 DWJ\n" +
            "大王滩 DZZ\n" +
            "大湾子 DFM\n" +
            "大兴沟 DXL\n" +
            "大兴 DXX\n" +
            "定西 DSJ\n" +
            "甸心 DXM\n" +
            "东乡 DXG\n" +
            "代县 DKV\n" +
            "定襄 DXV\n" +
            "东戌 RXP\n" +
            "东辛庄 DXD\n" +
            "德阳 DYW\n" +
            "丹阳 DYH\n" +
            "大雁 DYX\n" +
            "当阳 DYN\n" +
            "丹阳北 EXH\n" +
            "大英东 IAW\n" +
            "东淤地 DBV\n" +
            "大营 DYV\n" +
            "定远 EWH\n" +
            "岱岳 RYV\n" +
            "大元 DYZ\n" +
            "大营镇 DJP\n" +
            "大营子 DZD\n" +
            "大战场 DTJ\n" +
            "德州东 DIP\n" +
            "低庄 DVQ\n" +
            "东镇 DNV\n" +
            "道州 DFZ\n" +
            "东至 DCH\n" +
            "东庄 DZV\n" +
            "兑镇 DWV\n" +
            "豆庄 ROP\n" +
            "定州 DXP\n" +
            "大竹园 DZY\n" +
            "大杖子 DAP\n" +
            "豆张庄 RZP\n" +
            "峨边 EBW\n" +
            "二道沟门 RDP\n" +
            "二道湾 RDX\n" +
            "鄂尔多斯 EEC\n" +
            "二龙 RLD\n" +
            "二龙山屯 ELA\n" +
            "峨眉 EMW\n" +
            "二密河 RML\n" +
            "二营 RYJ\n" +
            "鄂州 ECN\n" +
            "福安 FAS\n" +
            "丰城 FCG\n" +
            "丰城南 FNG\n" +
            "肥东 FIH\n" +
            "发耳 FEM\n" +
            "富海 FHX\n" +
            "福海 FHR\n" +
            "凤凰城 FHT\n" +
            "奉化 FHH\n" +
            "富锦 FIB\n" +
            "范家屯 FTT\n" +
            "福利屯 FTB\n" +
            "丰乐镇 FZB\n" +
            "阜南 FNH\n" +
            "阜宁 AKH\n" +
            "抚宁 FNP\n" +
            "福清 FQS\n" +
            "福泉 VMW\n" +
            "丰水村 FSJ\n" +
            "丰顺 FUQ\n" +
            "繁峙 FSV\n" +
            "抚顺 FST\n" +
            "福山口 FKP\n" +
            "扶绥 FSZ\n" +
            "冯屯 FTX\n" +
            "浮图峪 FYP\n" +
            "富县东 FDY\n" +
            "凤县 FXY\n" +
            "富县 FEY\n" +
            "费县 FXK\n" +
            "凤阳 FUH\n" +
            "汾阳 FAV\n" +
            "扶余北 FBT\n" +
            "分宜 FYG\n" +
            "富源 FYM\n" +
            "扶余 FYT\n" +
            "富裕 FYX\n" +
            "抚州北 FBG\n" +
            "凤州 FZY\n" +
            "丰镇 FZC\n" +
            "范镇 VZK\n" +
            "固安 GFP\n" +
            "广安 VJW\n" +
            "高碑店 GBP\n" +
            "沟帮子 GBD\n" +
            "甘草店 GDJ\n" +
            "谷城 GCN\n" +
            "藁城 GEP\n" +
            "高村 GCV\n" +
            "古城镇 GZB\n" +
            "广德 GRH\n" +
            "贵定 GTW\n" +
            "贵定南 IDW\n" +
            "古东 GDV\n" +
            "贵港 GGZ\n" +
            "官高 GVP\n" +
            "葛根庙 GGT\n" +
            "干沟 GGL\n" +
            "甘谷 GGJ\n" +
            "高各庄 GGP\n" +
            "甘河 GAX\n" +
            "根河 GEX\n" +
            "郭家店 GDT\n" +
            "孤家子 GKT\n" +
            "古浪 GLJ\n" +
            "皋兰 GEJ\n" +
            "高楼房 GFM\n" +
            "归流河 GHT\n" +
            "关林 GLF\n" +
            "甘洛 VOW\n" +
            "郭磊庄 GLP\n" +
            "高密 GMK\n" +
            "公庙子 GMC\n" +
            "工农湖 GRT\n" +
            "广宁寺 GNT\n" +
            "广南卫 GNM\n" +
            "高平 GPF\n" +
            "甘泉北 GEY\n" +
            "共青城 GAG\n" +
            "甘旗卡 GQD\n" +
            "甘泉 GQY\n" +
            "高桥镇 GZD\n" +
            "赶水 GSW\n" +
            "灌水 GST\n" +
            "孤山口 GSP\n" +
            "果松 GSL\n" +
            "高山子 GSD\n" +
            "嘎什甸子 GXD\n" +
            "高台 GTJ\n" +
            "高滩 GAY\n" +
            "古田 GTS\n" +
            "官厅 GTP\n" +
            "官厅西 KEP\n" +
            "贵溪 GXG\n" +
            "涡阳 GYH\n" +
            "巩义 GXF\n" +
            "高邑 GIP\n" +
            "巩义南 GYF\n" +
            "广元南 GAW\n" +
            "固原 GUJ\n" +
            "菇园 GYL\n" +
            "公营子 GYD\n" +
            "光泽 GZS\n" +
            "古镇 GNQ\n" +
            "瓜州 GZJ\n" +
            "高州 GSQ\n" +
            "固镇 GEH\n" +
            "盖州 GXT\n" +
            "官字井 GOT\n" +
            "革镇堡 GZT\n" +
            "冠豸山 GSS\n" +
            "盖州西 GAT\n" +
            "红安 HWN\n" +
            "淮安南 AMH\n" +
            "红安西 VXN\n" +
            "海安县 HIH\n" +
            "黄柏 HBL\n" +
            "海北 HEB\n" +
            "鹤壁 HAF\n" +
            "华城 VCQ\n" +
            "合川 WKW\n" +
            "河唇 HCZ\n" +
            "汉川 HCN\n" +
            "海城 HCT\n" +
            "黑冲滩 HCJ\n" +
            "黄村 HCP\n" +
            "海城西 HXT\n" +
            "化德 HGC\n" +
            "洪洞 HDV\n" +
            "霍尔果斯 HFR\n" +
            "横峰 HFG\n" +
            "韩府湾 HXJ\n" +
            "汉沽 HGP\n" +
            "红光镇 IGW\n" +
            "浑河 HHT\n" +
            "红花沟 VHD\n" +
            "黄花筒 HUD\n" +
            "贺家店 HJJ\n" +
            "和静 HJR\n" +
            "红江 HFM\n" +
            "黑井 HIM\n" +
            "获嘉 HJF\n" +
            "河津 HJV\n" +
            "涵江 HJS\n" +
            "华家 HJT\n" +
            "杭锦后旗 HDC\n" +
            "河间西 HXP\n" +
            "花家庄 HJM\n" +
            "河口南 HKJ\n" +
            "黄口 KOH\n" +
            "湖口 HKG\n" +
            "呼兰 HUB\n" +
            "葫芦岛北 HPD\n" +
            "浩良河 HHB\n" +
            "哈拉海 HIT\n" +
            "鹤立 HOB\n" +
            "桦林 HIB\n" +
            "黄陵 ULY\n" +
            "海林 HRB\n" +
            "虎林 VLB\n" +
            "寒岭 HAT\n" +
            "和龙 HLL\n" +
            "海龙 HIL\n" +
            "哈拉苏 HAX\n" +
            "呼鲁斯太 VTJ\n" +
            "火连寨 HLT\n" +
            "黄梅 VEH\n" +
            "韩麻营 HYP\n" +
            "黄泥河 HHL\n" +
            "海宁 HNH\n" +
            "惠农 HMJ\n" +
            "和平 VAQ\n" +
            "花棚子 HZM\n" +
            "花桥 VQH\n" +
            "宏庆 HEY\n" +
            "怀仁 HRV\n" +
            "华容 HRN\n" +
            "华山北 HDY\n" +
            "黄松甸 HDL\n" +
            "和什托洛盖 VSR\n" +
            "红山 VSB\n" +
            "汉寿 VSQ\n" +
            "衡山 HSQ\n" +
            "黑水 HOT\n" +
            "惠山 VCH\n" +
            "虎什哈 HHP\n" +
            "红寺堡 HSJ\n" +
            "虎石台 HUT\n" +
            "海石湾 HSO\n" +
            "衡山西 HEQ\n" +
            "红砂岘 VSJ\n" +
            "黑台 HQB\n" +
            "桓台 VTK\n" +
            "和田 VTR\n" +
            "会同 VTQ\n" +
            "海坨子 HZT\n" +
            "黑旺 HWK\n" +
            "海湾 RWH\n" +
            "红星 VXB\n" +
            "徽县 HYY\n" +
            "红兴隆 VHB\n" +
            "换新天 VTB\n" +
            "红岘台 HTJ\n" +
            "红彦 VIX\n" +
            "合阳 HAY\n" +
            "海阳 HYK\n" +
            "衡阳东 HVQ\n" +
            "华蓥 HUW\n" +
            "汉阴 HQY\n" +
            "黄羊滩 HGJ\n" +
            "汉源 WHW\n" +
            "湟源 HNO\n" +
            "河源 VIQ\n" +
            "花园 HUN\n" +
            "黄羊镇 HYJ\n" +
            "湖州 VZH\n" +
            "化州 HZZ\n" +
            "黄州 VON\n" +
            "霍州 HZV\n" +
            "惠州西 VXQ\n" +
            "巨宝 JRT\n" +
            "靖边 JIY\n" +
            "金宝屯 JBD\n" +
            "晋城北 JEF\n" +
            "金昌 JCJ\n" +
            "鄄城 JCK\n" +
            "交城 JNV\n" +
            "建昌 JFD\n" +
            "峻德 JDB\n" +
            "井店 JFP\n" +
            "鸡东 JOB\n" +
            "江都 UDH\n" +
            "鸡冠山 JST\n" +
            "金沟屯 VGP\n" +
            "静海 JHP\n" +
            "金河 JHX\n" +
            "锦河 JHB\n" +
            "精河 JHR\n" +
            "精河南 JIR\n" +
            "江华 JHZ\n" +
            "建湖 AJH\n" +
            "纪家沟 VJD\n" +
            "晋江 JJS\n" +
            "江津 JJW\n" +
            "姜家 JJB\n" +
            "金坑 JKT\n" +
            "芨岭 JLJ\n" +
            "金马村 JMM\n" +
            "江门 JWQ\n" +
            "角美 JES\n" +
            "莒南 JOK\n" +
            "井南 JNP\n" +
            "建瓯 JVS\n" +
            "经棚 JPC\n" +
            "江桥 JQX\n" +
            "九三 SSX\n" +
            "金山北 EGH\n" +
            "京山 JCN\n" +
            "建始 JRN\n" +
            "嘉善 JSH\n" +
            "稷山 JVV\n" +
            "吉舒 JSL\n" +
            "建设 JET\n" +
            "甲山 JOP\n" +
            "建三江 JIB\n" +
            "嘉善南 EAH\n" +
            "金山屯 JTB\n" +
            "江所田 JOM\n" +
            "景泰 JTJ\n" +
            "九台南 JNL\n" +
            "吉文 JWX\n" +
            "进贤 JUG\n" +
            "莒县 JKK\n" +
            "嘉祥 JUK\n" +
            "介休 JXV\n" +
            "井陉 JJP\n" +
            "嘉兴 JXH\n" +
            "嘉兴南 EPH\n" +
            "夹心子 JXT\n" +
            "简阳 JYW\n" +
            "揭阳 JRQ\n" +
            "建阳 JYS\n" +
            "姜堰 UEH\n" +
            "巨野 JYK\n" +
            "江永 JYZ\n" +
            "靖远 JYJ\n" +
            "缙云 JYH\n" +
            "江源 SZL\n" +
            "济源 JYF\n" +
            "靖远西 JXJ\n" +
            "胶州北 JZK\n" +
            "焦作东 WEF\n" +
            "靖州 JEQ\n" +
            "荆州 JBN\n" +
            "金寨 JZH\n" +
            "晋州 JXP\n" +
            "胶州 JXK\n" +
            "锦州南 JOD\n" +
            "焦作 JOF\n" +
            "旧庄窝 JVP\n" +
            "金杖子 JYD\n" +
            "开安 KAT\n" +
            "库车 KCR\n" +
            "康城 KCP\n" +
            "库都尔 KDX\n" +
            "宽甸 KDT\n" +
            "克东 KOB\n" +
            "开江 KAW\n" +
            "康金井 KJB\n" +
            "喀喇其 KQX\n" +
            "开鲁 KLC\n" +
            "克拉玛依 KHR\n" +
            "口前 KQL\n" +
            "奎山 KAB\n" +
            "昆山 KSH\n" +
            "克山 KSB\n" +
            "开通 KTT\n" +
            "康熙岭 KXZ\n" +
            "昆阳 KAM\n" +
            "克一河 KHX\n" +
            "开原西 KXT\n" +
            "康庄 KZP\n" +
            "来宾 UBZ\n" +
            "老边 LLT\n" +
            "灵宝西 LPF\n" +
            "龙川 LUQ\n" +
            "乐昌 LCQ\n" +
            "黎城 UCP\n" +
            "聊城 UCK\n" +
            "蓝村 LCK\n" +
            "两当 LDY\n" +
            "林东 LRC\n" +
            "乐都 LDO\n" +
            "梁底下 LDP\n" +
            "六道河子 LVP\n" +
            "鲁番 LVM\n" +
            "廊坊 LJP\n" +
            "落垡 LOP\n" +
            "廊坊北 LFP\n" +
            "老府 UFD\n" +
            "兰岗 LNB\n" +
            "龙骨甸 LGM\n" +
            "芦沟 LOM\n" +
            "龙沟 LGJ\n" +
            "拉古 LGB\n" +
            "临海 UFH\n" +
            "林海 LXX\n" +
            "拉哈 LHX\n" +
            "凌海 JID\n" +
            "柳河 LNL\n" +
            "六合 KLH\n" +
            "龙华 LHP\n" +
            "滦河沿 UNP\n" +
            "六合镇 LEX\n" +
            "亮甲店 LRT\n" +
            "刘家店 UDT\n" +
            "刘家河 LVT\n" +
            "连江 LKS\n" +
            "李家 LJB\n" +
            "罗江 LJW\n" +
            "廉江 LJZ\n" +
            "庐江 UJH\n" +
            "两家 UJT\n" +
            "龙江 LJX\n" +
            "龙嘉 UJL\n" +
            "莲江口 LHB\n" +
            "蔺家楼 ULK\n" +
            "李家坪 LIJ\n" +
            "兰考 LKF\n" +
            "林口 LKB\n" +
            "路口铺 LKQ\n" +
            "老莱 LAX\n" +
            "拉林 LAB\n" +
            "陆良 LRM\n" +
            "龙里 LLW\n" +
            "零陵 UWZ\n" +
            "临澧 LWQ\n" +
            "兰棱 LLB\n" +
            "卢龙 UAP\n" +
            "喇嘛甸 LMX\n" +
            "里木店 LMB\n" +
            "洛门 LMJ\n" +
            "龙南 UNG\n" +
            "梁平 UQW\n" +
            "罗平 LPM\n" +
            "落坡岭 LPP\n" +
            "六盘山 UPJ\n" +
            "乐平市 LPG\n" +
            "临清 UQK\n" +
            "龙泉寺 UQJ\n" +
            "乐山北 UTW\n" +
            "乐善村 LUM\n" +
            "冷水江东 UDQ\n" +
            "连山关 LGT\n" +
            "流水沟 USP\n" +
            "陵水 LIQ\n" +
            "罗山 LRN\n" +
            "鲁山 LAF\n" +
            "丽水 USH\n" +
            "梁山 LMK\n" +
            "灵石 LSV\n" +
            "露水河 LUL\n" +
            "庐山 LSG\n" +
            "林盛堡 LBT\n" +
            "柳树屯 LSD\n" +
            "龙山镇 LAS\n" +
            "梨树镇 LSB\n" +
            "李石寨 LET\n" +
            "黎塘 LTZ\n" +
            "轮台 LAR\n" +
            "芦台 LTP\n" +
            "龙塘坝 LBM\n" +
            "濑湍 LVZ\n" +
            "骆驼巷 LTJ\n" +
            "李旺 VLJ\n" +
            "莱芜东 LWK\n" +
            "狼尾山 LRJ\n" +
            "灵武 LNJ\n" +
            "莱芜西 UXK\n" +
            "朗乡 LXB\n" +
            "陇县 LXY\n" +
            "临湘 LXQ\n" +
            "芦溪 LUG\n" +
            "莱西 LXK\n" +
            "林西 LXC\n" +
            "滦县 UXP\n" +
            "略阳 LYY\n" +
            "莱阳 LYK\n" +
            "辽阳 LYT\n" +
            "临沂北 UYK\n" +
            "凌源东 LDD\n" +
            "连云港 UIH\n" +
            "临颍 LNF\n" +
            "老营 LXL\n" +
            "龙游 LMH\n" +
            "罗源 LVS\n" +
            "林源 LYX\n" +
            "涟源 LAQ\n" +
            "涞源 LYP\n" +
            "耒阳西 LPQ\n" +
            "临泽 LEJ\n" +
            "龙爪沟 LZT\n" +
            "雷州 UAQ\n" +
            "六枝 LIW\n" +
            "鹿寨 LIZ\n" +
            "来舟 LZS\n" +
            "龙镇 LZA\n" +
            "拉鲊 LEM\n" +
            "马鞍山 MAH\n" +
            "毛坝 MBY\n" +
            "毛坝关 MGY\n" +
            "麻城北 MBN\n" +
            "渑池 MCF\n" +
            "明城 MCL\n" +
            "庙城 MAP\n" +
            "渑池南 MNF\n" +
            "茅草坪 KPM\n" +
            "猛洞河 MUQ\n" +
            "磨刀石 MOB\n" +
            "弥渡 MDF\n" +
            "帽儿山 MRB\n" +
            "明港 MGN\n" +
            "梅河口 MHL\n" +
            "马皇 MHZ\n" +
            "孟家岗 MGB\n" +
            "美兰 MHQ\n" +
            "汨罗东 MQQ\n" +
            "马莲河 MHB\n" +
            "茅岭 MLZ\n" +
            "庙岭 MLL\n" +
            "茂林 MLD\n" +
            "穆棱 MLB\n" +
            "马林 MID\n" +
            "马龙 MGM\n" +
            "木里图 MUD\n" +
            "汨罗 MLQ\n" +
            "玛纳斯湖 MNR\n" +
            "冕宁 UGW\n" +
            "沐滂 MPQ\n" +
            "马桥河 MQB\n" +
            "闽清 MQS\n" +
            "民权 MQF\n" +
            "明水河 MUT\n" +
            "麻山 MAB\n" +
            "眉山 MSW\n" +
            "漫水湾 MKW\n" +
            "茂舍祖 MOM\n" +
            "米沙子 MST\n" +
            "美溪 MEB\n" +
            "勉县 MVY\n" +
            "麻阳 MVQ\n" +
            "密云北 MUP\n" +
            "米易 MMW\n" +
            "麦园 MYS\n" +
            "墨玉 MUR\n" +
            "庙庄 MZJ\n" +
            "米脂 MEY\n" +
            "明珠 MFQ\n" +
            "宁安 NAB\n" +
            "农安 NAT\n" +
            "南博山 NBK\n" +
            "南仇 NCK\n" +
            "南城司 NSP\n" +
            "宁村 NCZ\n" +
            "宁德 NES\n" +
            "南观村 NGP\n" +
            "南宫东 NFP\n" +
            "南关岭 NLT\n" +
            "宁国 NNH\n" +
            "宁海 NHH\n" +
            "南河川 NHJ\n" +
            "南华 NHS\n" +
            "泥河子 NHD\n" +
            "宁家 NVT\n" +
            "南靖 NJS\n" +
            "牛家 NJB\n" +
            "能家 NJD\n" +
            "南口 NKP\n" +
            "南口前 NKT\n" +
            "南朗 NNQ\n" +
            "乃林 NLD\n" +
            "尼勒克 NIR\n" +
            "那罗 ULZ\n" +
            "宁陵县 NLF\n" +
            "奈曼 NMD\n" +
            "宁明 NMZ\n" +
            "南木 NMX\n" +
            "南平南 NNS\n" +
            "那铺 NPZ\n" +
            "南桥 NQD\n" +
            "那曲 NQO\n" +
            "暖泉 NQJ\n" +
            "南台 NTT\n" +
            "南头 NOQ\n" +
            "宁武 NWV\n" +
            "南湾子 NWP\n" +
            "南翔北 NEH\n" +
            "宁乡 NXQ\n" +
            "内乡 NXF\n" +
            "牛心台 NXT\n" +
            "南峪 NUP\n" +
            "娘子关 NIP\n" +
            "南召 NAF\n" +
            "南杂木 NZT\n" +
            "平安 PAL\n" +
            "蓬安 PAW\n" +
            "平安驿 PNO\n" +
            "磐安镇 PAJ\n" +
            "平安镇 PZT\n" +
            "蒲城东 PEY\n" +
            "蒲城 PCY\n" +
            "裴德 PDB\n" +
            "偏店 PRP\n" +
            "平顶山西 BFF\n" +
            "坡底下 PXJ\n" +
            "瓢儿屯 PRT\n" +
            "平房 PFB\n" +
            "平岗 PGL\n" +
            "平关 PGM\n" +
            "盘关 PAM\n" +
            "平果 PGZ\n" +
            "徘徊北 PHP\n" +
            "平河口 PHM\n" +
            "盘锦北 PBD\n" +
            "潘家店 PDP\n" +
            "皮口 PKT\n" +
            "普兰店 PLT\n" +
            "偏岭 PNT\n" +
            "平山 PSB\n" +
            "彭山 PSW\n" +
            "皮山 PSR\n" +
            "彭水 PHW\n" +
            "磐石 PSL\n" +
            "平社 PSV\n" +
            "平台 PVT\n" +
            "平田 PTM\n" +
            "莆田 PTS\n" +
            "葡萄菁 PTW\n" +
            "普湾 PWT\n" +
            "平旺 PWV\n" +
            "平型关 PGV\n" +
            "普雄 POW\n" +
            "郫县 PWW\n" +
            "平洋 PYX\n" +
            "彭阳 PYJ\n" +
            "平遥 PYV\n" +
            "平邑 PIK\n" +
            "平原堡 PPJ\n" +
            "平原 PYK\n" +
            "平峪 PYP\n" +
            "彭泽 PZG\n" +
            "邳州 PJH\n" +
            "平庄 PZD\n" +
            "泡子 POD\n" +
            "平庄南 PND\n" +
            "乾安 QOT\n" +
            "庆安 QAB\n" +
            "迁安 QQP\n" +
            "祁东北 QRQ\n" +
            "七甸 QDM\n" +
            "曲阜东 QAK\n" +
            "庆丰 QFT\n" +
            "奇峰塔 QVP\n" +
            "曲阜 QFK\n" +
            "琼海 QYQ\n" +
            "秦皇岛 QTP\n" +
            "千河 QUY\n" +
            "清河 QIP\n" +
            "清河门 QHD\n" +
            "清华园 QHP\n" +
            "渠旧 QJZ\n" +
            "綦江 QJW\n" +
            "潜江 QJN\n" +
            "全椒 INH\n" +
            "秦家 QJB\n" +
            "祁家堡 QBT\n" +
            "清涧县 QNY\n" +
            "秦家庄 QZV\n" +
            "七里河 QLD\n" +
            "渠黎 QLZ\n" +
            "秦岭 QLY\n" +
            "青龙山 QGH\n" +
            "祁门 QIH\n" +
            "前磨头 QMP\n" +
            "青山 QSB\n" +
            "确山 QSN\n" +
            "清水 QUJ\n" +
            "前山 QXQ\n" +
            "戚墅堰 QYH\n" +
            "青田 QVH\n" +
            "桥头 QAT\n" +
            "青铜峡 QTJ\n" +
            "前卫 QWD\n" +
            "前苇塘 QWP\n" +
            "渠县 QRW\n" +
            "祁县 QXV\n" +
            "青县 QXP\n" +
            "桥西 QXJ\n" +
            "清徐 QUV\n" +
            "旗下营 QXC\n" +
            "千阳 QOY\n" +
            "沁阳 QYF\n" +
            "泉阳 QYL\n" +
            "祁阳北 QVQ\n" +
            "七营 QYJ\n" +
            "庆阳山 QSJ\n" +
            "清远 QBQ\n" +
            "清原 QYT\n" +
            "钦州东 QDZ\n" +
            "钦州 QRZ\n" +
            "青州市 QZK\n" +
            "瑞安 RAH\n" +
            "荣昌 RCW\n" +
            "瑞昌 RCG\n" +
            "如皋 RBH\n" +
            "容桂 RUQ\n" +
            "任丘 RQP\n" +
            "乳山 ROK\n" +
            "融水 RSZ\n" +
            "热水 RSD\n" +
            "容县 RXZ\n" +
            "饶阳 RVP\n" +
            "汝阳 RYF\n" +
            "绕阳河 RHD\n" +
            "汝州 ROF\n" +
            "石坝 OBJ\n" +
            "上板城 SBP\n" +
            "施秉 AQW\n" +
            "上板城南 OBP\n" +
            "世博园 ZWT\n" +
            "双城北 SBB\n" +
            "商城 SWN\n" +
            "莎车 SCR\n" +
            "顺昌 SCS\n" +
            "舒城 OCH\n" +
            "神池 SMV\n" +
            "沙城 SCP\n" +
            "石城 SCT\n" +
            "山城镇 SCL\n" +
            "山丹 SDJ\n" +
            "顺德 ORQ\n" +
            "绥德 ODY\n" +
            "邵东 SOQ\n" +
            "水洞 SIL\n" +
            "商都 SXC\n" +
            "十渡 SEP\n" +
            "四道湾 OUD\n" +
            "顺德学院 OJQ\n" +
            "绅坊 OLH\n" +
            "双丰 OFB\n" +
            "四方台 STB\n" +
            "水富 OTW\n" +
            "三关口 OKJ\n" +
            "桑根达来 OGC\n" +
            "韶关 SNQ\n" +
            "上高镇 SVK\n" +
            "上杭 JBS\n" +
            "沙海 SED\n" +
            "松河 SBM\n" +
            "沙河 SHP\n" +
            "沙河口 SKT\n" +
            "赛汗塔拉 SHC\n" +
            "沙河市 VOP\n" +
            "沙后所 SSD\n" +
            "山河屯 SHL\n" +
            "三河县 OXP\n" +
            "四合永 OHD\n" +
            "三汇镇 OZW\n" +
            "双河镇 SEL\n" +
            "石河子 SZR\n" +
            "三合庄 SVP\n" +
            "三家店 ODP\n" +
            "水家湖 SQH\n" +
            "沈家河 OJJ\n" +
            "松江河 SJL\n" +
            "尚家 SJB\n" +
            "孙家 SUB\n" +
            "沈家 OJB\n" +
            "松江 SAH\n" +
            "三江口 SKD\n" +
            "司家岭 OLK\n" +
            "松江南 IMH\n" +
            "石景山南 SRP\n" +
            "邵家堂 SJJ\n" +
            "三江县 SOZ\n" +
            "三家寨 SMM\n" +
            "十家子 SJD\n" +
            "松江镇 OZL\n" +
            "施家嘴 SHM\n" +
            "深井子 SWT\n" +
            "什里店 OMP\n" +
            "疏勒 SUR\n" +
            "疏勒河 SHJ\n" +
            "舍力虎 VLD\n" +
            "石磷 SPB\n" +
            "双辽 ZJD\n" +
            "绥棱 SIB\n" +
            "石岭 SOL\n" +
            "石林 SLM\n" +
            "石林南 LNM\n" +
            "石龙 SLQ\n" +
            "萨拉齐 SLC\n" +
            "索伦 SNT\n" +
            "商洛 OLY\n" +
            "沙岭子 SLP\n" +
            "石门县北 VFQ\n" +
            "三门峡南 SCF\n" +
            "三门县 OQH\n" +
            "石门县 OMQ\n" +
            "三门峡西 SXF\n" +
            "肃宁 SYP\n" +
            "宋 SOB\n" +
            "双牌 SBZ\n" +
            "四平东 PPT\n" +
            "遂平 SON\n" +
            "沙坡头 SFJ\n" +
            "商丘南 SPF\n" +
            "水泉 SID\n" +
            "石泉县 SXY\n" +
            "石桥子 SQT\n" +
            "石人城 SRB\n" +
            "石人 SRL\n" +
            "山市 SQB\n" +
            "神树 SWB\n" +
            "鄯善 SSR\n" +
            "三水 SJQ\n" +
            "泗水 OSK\n" +
            "石山 SAD\n" +
            "松树 SFT\n" +
            "首山 SAT\n" +
            "三十家 SRD\n" +
            "三十里堡 SST\n" +
            "松树镇 SSL\n" +
            "松桃 MZQ\n" +
            "索图罕 SHX\n" +
            "三堂集 SDH\n" +
            "石头 OTB\n" +
            "神头 SEV\n" +
            "沙沱 SFM\n" +
            "上万 SWP\n" +
            "孙吴 SKB\n" +
            "沙湾县 SXR\n" +
            "遂溪 SXZ\n" +
            "沙县 SAS\n" +
            "歙县 OVH\n" +
            "绍兴 SOH\n" +
            "石岘 SXL\n" +
            "上西铺 SXM\n" +
            "石峡子 SXJ\n" +
            "绥阳 SYB\n" +
            "沭阳 FMH\n" +
            "寿阳 SYV\n" +
            "水洋 OYP\n" +
            "三阳川 SYJ\n" +
            "上腰墩 SPJ\n" +
            "三营 OEJ\n" +
            "顺义 SOP\n" +
            "三义井 OYD\n" +
            "三源浦 SYL\n" +
            "三原 SAY\n" +
            "上虞 BDH\n" +
            "上园 SUD\n" +
            "水源 OYJ\n" +
            "桑园子 SAJ\n" +
            "绥中北 SND\n" +
            "苏州北 OHH\n" +
            "宿州东 SRH\n" +
            "深圳东 BJQ\n" +
            "深州 OZP\n" +
            "孙镇 OZY\n" +
            "绥中 SZD\n" +
            "尚志 SZB\n" +
            "师庄 SNM\n" +
            "松滋 SIN\n" +
            "师宗 SEM\n" +
            "苏州园区 KAH\n" +
            "苏州新区 ITH\n" +
            "泰安 TMK\n" +
            "台安 TID\n" +
            "通安驿 TAJ\n" +
            "桐柏 TBF\n" +
            "通北 TBB\n" +
            "汤池 TCX\n" +
            "桐城 TTH\n" +
            "郯城 TZK\n" +
            "铁厂 TCL\n" +
            "桃村 TCK\n" +
            "通道 TRQ\n" +
            "田东 TDZ\n" +
            "天岗 TGL\n" +
            "土贵乌拉 TGC\n" +
            "通沟 TOL\n" +
            "太谷 TGV\n" +
            "塔哈 THX\n" +
            "棠海 THM\n" +
            "唐河 THF\n" +
            "泰和 THG\n" +
            "太湖 TKH\n" +
            "团结 TIX\n" +
            "谭家井 TNJ\n" +
            "陶家屯 TOT\n" +
            "唐家湾 PDQ\n" +
            "统军庄 TZP\n" +
            "泰康 TKX\n" +
            "吐列毛杜 TMD\n" +
            "图里河 TEX\n" +
            "亭亮 TIZ\n" +
            "田林 TFZ\n" +
            "铜陵 TJH\n" +
            "铁力 TLB\n" +
            "铁岭西 PXT\n" +
            "天门 TMN\n" +
            "天门南 TNN\n" +
            "太姥山 TLS\n" +
            "土牧尔台 TRC\n" +
            "土门子 TCJ\n" +
            "潼南 TVW\n" +
            "洮南 TVT\n" +
            "太平川 TIT\n" +
            "太平镇 TEB\n" +
            "图强 TQX\n" +
            "台前 TTK\n" +
            "天桥岭 TQL\n" +
            "土桥子 TQJ\n" +
            "汤山城 TCT\n" +
            "桃山 TAB\n" +
            "塔石嘴 TIM\n" +
            "通途 TUT\n" +
            "汤旺河 THB\n" +
            "同心 TXJ\n" +
            "土溪 TSW\n" +
            "桐乡 TCH\n" +
            "田阳 TRZ\n" +
            "天义 TND\n" +
            "汤阴 TYF\n" +
            "驼腰岭 TIL\n" +
            "太阳山 TYJ\n" +
            "汤原 TYB\n" +
            "塔崖驿 TYP\n" +
            "滕州东 TEK\n" +
            "台州 TZH\n" +
            "天祝 TZJ\n" +
            "滕州 TXK\n" +
            "天镇 TZV\n" +
            "桐子林 TEW\n" +
            "天柱山 QWH\n" +
            "文安 WBP\n" +
            "武安 WAP\n" +
            "王安镇 WVP\n" +
            "旺苍 WEW\n" +
            "五叉沟 WCT\n" +
            "文昌 WEQ\n" +
            "温春 WDB\n" +
            "五大连池 WRB\n" +
            "文登 WBK\n" +
            "五道沟 WDL\n" +
            "五道河 WHP\n" +
            "文地 WNZ\n" +
            "卫东 WVT\n" +
            "武当山 WRN\n" +
            "望都 WDP\n" +
            "乌尔旗汗 WHX\n" +
            "潍坊 WFK\n" +
            "万发屯 WFB\n" +
            "王府 WUT\n" +
            "瓦房店西 WXT\n" +
            "王岗 WGB\n" +
            "武功 WGY\n" +
            "湾沟 WGL\n" +
            "吴官田 WGM\n" +
            "乌海 WVC\n" +
            "苇河 WHB\n" +
            "卫辉 WHF\n" +
            "吴家川 WCJ\n" +
            "五家 WUB\n" +
            "威箐 WAM\n" +
            "午汲 WJP\n" +
            "渭津 WJL\n" +
            "王家湾 WJJ\n" +
            "倭肯 WQB\n" +
            "五棵树 WKT\n" +
            "五龙背 WBT\n" +
            "乌兰哈达 WLC\n" +
            "万乐 WEB\n" +
            "瓦拉干 WVX\n" +
            "温岭 VHH\n" +
            "五莲 WLK\n" +
            "乌拉特前旗 WQC\n" +
            "乌拉山 WSC\n" +
            "卧里屯 WLX\n" +
            "渭南北 WBY\n" +
            "乌奴耳 WRX\n" +
            "万宁 WNQ\n" +
            "万年 WWG\n" +
            "渭南南 WVY\n" +
            "渭南镇 WNJ\n" +
            "沃皮 WPT\n" +
            "吴堡 WUY\n" +
            "吴桥 WUP\n" +
            "汪清 WQL\n" +
            "武清 WWP\n" +
            "武山 WSJ\n" +
            "文水 WEV\n" +
            "魏善庄 WSP\n" +
            "王瞳 WTP\n" +
            "五台山 WSV\n" +
            "王团庄 WZJ\n" +
            "五五 WVR\n" +
            "无锡东 WGH\n" +
            "卫星 WVB\n" +
            "闻喜 WXV\n" +
            "武乡 WVV\n" +
            "无锡新区 IFH\n" +
            "武穴 WXN\n" +
            "吴圩 WYZ\n" +
            "王杨 WYB\n" +
            "五营 WWB\n" +
            "武义 RYH\n" +
            "瓦窑田 WIM\n" +
            "五原 WYC\n" +
            "苇子沟 WZL\n" +
            "韦庄 WZY\n" +
            "五寨 WZV\n" +
            "王兆屯 WZB\n" +
            "微子镇 WQP\n" +
            "魏杖子 WKD\n" +
            "新安 EAM\n" +
            "兴安 XAZ\n" +
            "新安县 XAF\n" +
            "新保安 XAP\n" +
            "下板城 EBP\n" +
            "西八里 XLP\n" +
            "宣城 ECH\n" +
            "兴城 XCD\n" +
            "小村 XEM\n" +
            "新绰源 XRX\n" +
            "下城子 XCB\n" +
            "新城子 XCT\n" +
            "喜德 EDW\n" +
            "小得江 EJM\n" +
            "西大庙 XMP\n" +
            "小董 XEZ\n" +
            "小东 XOD\n" +
            "息烽 XFW\n" +
            "信丰 EFG\n" +
            "襄汾 XFV\n" +
            "新干 EGG\n" +
            "孝感 XGN\n" +
            "西固城 XUJ\n" +
            "夏官营 XGJ\n" +
            "西岗子 NBB\n" +
            "襄河 XXB\n" +
            "新和 XIR\n" +
            "宣和 XWJ\n" +
            "斜河涧 EEP\n" +
            "新华屯 XAX\n" +
            "新华 XHB\n" +
            "新化 EHQ\n" +
            "宣化 XHP\n" +
            "兴和西 XEC\n" +
            "小河沿 XYD\n" +
            "下花园 XYP\n" +
            "小河镇 EKY\n" +
            "徐家 XJB\n" +
            "峡江 EJG\n" +
            "新绛 XJV\n" +
            "辛集 ENP\n" +
            "新江 XJM\n" +
            "西街口 EKM\n" +
            "许家屯 XJT\n" +
            "许家台 XTJ\n" +
            "谢家镇 XMT\n" +
            "兴凯 EKB\n" +
            "小榄 EAQ\n" +
            "香兰 XNB\n" +
            "兴隆店 XDD\n" +
            "新乐 ELP\n" +
            "新林 XPX\n" +
            "小岭 XLB\n" +
            "新李 XLJ\n" +
            "西林 XYB\n" +
            "西柳 GCT\n" +
            "仙林 XPH\n" +
            "新立屯 XLD\n" +
            "兴隆镇 XZB\n" +
            "新立镇 XGT\n" +
            "新民 XMD\n" +
            "西麻山 XMB\n" +
            "下马塘 XAT\n" +
            "孝南 XNV\n" +
            "咸宁北 XRN\n" +
            "兴宁 ENQ\n" +
            "咸宁 XNN\n" +
            "犀浦东 XAW\n" +
            "西平 XPN\n" +
            "兴平 XPY\n" +
            "新坪田 XPM\n" +
            "霞浦 XOS\n" +
            "溆浦 EPQ\n" +
            "犀浦 XIW\n" +
            "新青 XQB\n" +
            "新邱 XQD\n" +
            "兴泉堡 XQJ\n" +
            "仙人桥 XRL\n" +
            "小寺沟 ESP\n" +
            "杏树 XSB\n" +
            "夏石 XIZ\n" +
            "浠水 XZN\n" +
            "下社 XSV\n" +
            "徐水 XSP\n" +
            "小哨 XAM\n" +
            "新松浦 XOB\n" +
            "杏树屯 XDT\n" +
            "许三湾 XSJ\n" +
            "湘潭 XTQ\n" +
            "邢台 XTP\n" +
            "仙桃西 XAN\n" +
            "下台子 EIP\n" +
            "徐闻 XJQ\n" +
            "新窝铺 EPD\n" +
            "修武 XWF\n" +
            "新县 XSN\n" +
            "息县 ENN\n" +
            "西乡 XQY\n" +
            "湘乡 XXQ\n" +
            "西峡 XIF\n" +
            "孝西 XOV\n" +
            "小新街 XXM\n" +
            "新兴县 XGQ\n" +
            "西小召 XZC\n" +
            "小西庄 XXP\n" +
            "向阳 XDB\n" +
            "旬阳 XUY\n" +
            "旬阳北 XBY\n" +
            "襄阳东 XWN\n" +
            "兴业 SNZ\n" +
            "小雨谷 XHM\n" +
            "信宜 EEQ\n" +
            "小月旧 XFM\n" +
            "小扬气 XYX\n" +
            "祥云 EXM\n" +
            "襄垣 EIF\n" +
            "夏邑县 EJH\n" +
            "新友谊 EYB\n" +
            "新阳镇 XZJ\n" +
            "徐州东 UUH\n" +
            "新帐房 XZX\n" +
            "悬钟 XRP\n" +
            "新肇 XZT\n" +
            "忻州 XXV\n" +
            "汐子 XZD\n" +
            "西哲里木 XRD\n" +
            "新杖子 ERP\n" +
            "姚安 YAC\n" +
            "依安 YAX\n" +
            "永安 YAS\n" +
            "永安乡 YNB\n" +
            "亚布力 YBB\n" +
            "元宝山 YUD\n" +
            "羊草 YAB\n" +
            "秧草地 YKM\n" +
            "阳澄湖 AIH\n" +
            "迎春 YYB\n" +
            "叶城 YER\n" +
            "盐池 YKJ\n" +
            "砚川 YYY\n" +
            "阳春 YQQ\n" +
            "宜城 YIN\n" +
            "应城 YHN\n" +
            "禹城 YCK\n" +
            "晏城 YEK\n" +
            "羊场 YED\n" +
            "阳城 YNF\n" +
            "阳岔 YAL\n" +
            "郓城 YPK\n" +
            "雁翅 YAP\n" +
            "云彩岭 ACP\n" +
            "虞城县 IXH\n" +
            "营城子 YCT\n" +
            "永登 YDJ\n" +
            "英德 YDQ\n" +
            "尹地 YDM\n" +
            "永定 YGS\n" +
            "雁荡山 YGH\n" +
            "于都 YDG\n" +
            "园墩 YAJ\n" +
            "英德西 IIQ\n" +
            "永丰营 YYM\n" +
            "杨岗 YRB\n" +
            "阳高 YOV\n" +
            "阳谷 YIK\n" +
            "友好 YOB\n" +
            "余杭 EVH\n" +
            "沿河城 YHP\n" +
            "岩会 AEP\n" +
            "羊臼河 YHM\n" +
            "永嘉 URH\n" +
            "营街 YAM\n" +
            "盐津 AEW\n" +
            "余江 YHG\n" +
            "燕郊 AJP\n" +
            "姚家 YAT\n" +
            "岳家井 YGJ\n" +
            "一间堡 YJT\n" +
            "英吉沙 YIR\n" +
            "云居寺 AFP\n" +
            "燕家庄 AZK\n" +
            "永康 RFH\n" +
            "营口东 YGT\n" +
            "银浪 YJX\n" +
            "永郎 YLW\n" +
            "宜良北 YSM\n" +
            "永乐店 YDY\n" +
            "伊拉哈 YLX\n" +
            "伊林 YLB\n" +
            "杨陵 YSY\n" +
            "彝良 ALW\n" +
            "杨林 YLM\n" +
            "余粮堡 YLD\n" +
            "杨柳青 YQP\n" +
            "月亮田 YUM\n" +
            "亚龙湾 TWQ\n" +
            "义马 YMF\n" +
            "玉门 YXJ\n" +
            "云梦 YMN\n" +
            "元谋 YMM\n" +
            "阳明堡 YVV\n" +
            "一面山 YST\n" +
            "沂南 YNK\n" +
            "宜耐 YVM\n" +
            "伊宁东 YNR\n" +
            "营盘水 YZJ\n" +
            "羊堡 ABM\n" +
            "阳泉北 YPP\n" +
            "乐清 UPH\n" +
            "焉耆 YSR\n" +
            "源迁 AQK\n" +
            "姚千户屯 YQT\n" +
            "阳曲 YQV\n" +
            "榆树沟 YGP\n" +
            "月山 YBF\n" +
            "玉石 YSJ\n" +
            "偃师 YSF\n" +
            "沂水 YUK\n" +
            "榆社 YSV\n" +
            "窑上 ASP\n" +
            "元氏 YSP\n" +
            "杨树岭 YAD\n" +
            "野三坡 AIP\n" +
            "榆树屯 YSX\n" +
            "榆树台 YUT\n" +
            "鹰手营子 YIP\n" +
            "源潭 YTQ\n" +
            "牙屯堡 YTZ\n" +
            "烟筒山 YSL\n" +
            "烟筒屯 YUX\n" +
            "羊尾哨 YWM\n" +
            "越西 YHW\n" +
            "攸县 YOG\n" +
            "玉溪 YXM\n" +
            "永修 ACG\n" +
            "弋阳 YIG\n" +
            "酉阳 AFW\n" +
            "余姚 YYH\n" +
            "岳阳东 YIQ\n" +
            "阳邑 ARP\n" +
            "鸭园 YYL\n" +
            "鸳鸯镇 YYJ\n" +
            "燕子砭 YZY\n" +
            "宜州 YSZ\n" +
            "仪征 UZH\n" +
            "兖州 YZK\n" +
            "迤资 YQM\n" +
            "羊者窝 AEM\n" +
            "杨杖子 YZD\n" +
            "镇安 ZEY\n" +
            "治安 ZAD\n" +
            "招柏 ZBP\n" +
            "张百湾 ZUP\n" +
            "枝城 ZCN\n" +
            "子长 ZHY\n" +
            "诸城 ZQK\n" +
            "邹城 ZIK\n" +
            "赵城 ZCV\n" +
            "章党 ZHT\n" +
            "正定 ZDP\n" +
            "肇东 ZDB\n" +
            "照福铺 ZFM\n" +
            "章古台 ZGD\n" +
            "赵光 ZGB\n" +
            "中和 ZHX\n" +
            "中华门 VNH\n" +
            "枝江北 ZIN\n" +
            "钟家村 ZJY\n" +
            "朱家沟 ZUB\n" +
            "紫荆关 ZYP\n" +
            "周家 ZOB\n" +
            "诸暨 ZDH\n" +
            "镇江南 ZEH\n" +
            "周家屯 ZOD\n" +
            "褚家湾 CWJ\n" +
            "湛江西 ZWQ\n" +
            "朱家窑 ZUJ\n" +
            "曾家坪子 ZBW\n" +
            "张兰 ZLV\n" +
            "镇赉 ZLT\n" +
            "枣林 ZIV\n" +
            "扎鲁特 ZLD\n" +
            "扎赉诺尔西 ZXX\n" +
            "樟木头 ZOQ\n" +
            "中牟 ZGF\n" +
            "中宁东 ZDJ\n" +
            "中宁 VNJ\n" +
            "中宁南 ZNJ\n" +
            "镇平 ZPF\n" +
            "漳平 ZPS\n" +
            "泽普 ZPR\n" +
            "枣强 ZVP\n" +
            "张桥 ZQY\n" +
            "章丘 ZTK\n" +
            "朱日和 ZRC\n" +
            "泽润里 ZLM\n" +
            "中山北 ZGQ\n" +
            "樟树东 ZOG\n" +
            "中山 ZSQ\n" +
            "柞水 ZSY\n" +
            "钟山 ZSZ\n" +
            "樟树 ZSG\n" +
            "珠窝 ZOP\n" +
            "张维屯 ZWB\n" +
            "彰武 ZWD\n" +
            "棕溪 ZOY\n" +
            "钟祥 ZTN\n" +
            "资溪 ZXS\n" +
            "镇西 ZVT\n" +
            "张辛 ZIP\n" +
            "正镶白旗 ZXC\n" +
            "紫阳 ZVY\n" +
            "枣阳 ZYN\n" +
            "竹园坝 ZAW\n" +
            "张掖 ZYJ\n" +
            "镇远 ZUW\n" +
            "朱杨溪 ZXW\n" +
            "漳州东 GOS\n" +
            "漳州 ZUS\n" +
            "壮志 ZUX\n" +
            "子洲 ZZY\n" +
            "中寨 ZZM\n" +
            "涿州 ZXP\n" +
            "咋子 ZAL\n" +
            "卓资山 ZZC\n" +
            "株洲西 ZAQ\n" +
            "安仁 ARG\n" +
            "安阳东 ADF\n" +
            "栟茶 FWH\n" +
            "保定东 BMP\n" +
            "滨海 FHP\n" +
            "滨海北 FCP\n" +
            "宝鸡南 BBY\n" +
            "宝清 BUB\n" +
            "彬县 BXY\n" +
            "宾阳 UKZ\n" +
            "巢湖东 GUH\n" +
            "从江 KNW\n" +
            "长临河 FVH\n" +
            "茶陵南 CNG\n" +
            "长庆桥 CQJ\n" +
            "长寿北 COW\n" +
            "潮汕 CBQ\n" +
            "长武 CWY\n" +
            "长兴 CBH\n" +
            "长阳 CYN\n" +
            "潮阳 CNQ\n" +
            "东安东 DCZ\n" +
            "东戴河 RDD\n" +
            "东二道河 DRB\n" +
            "东莞 RTQ\n" +
            "大苴 DIM\n" +
            "大荔 DNY\n" +
            "大青沟 DSD\n" +
            "德清 DRH\n" +
            "大通西 DTO\n" +
            "德兴 DWG\n" +
            "丹霞山 IRQ\n" +
            "大冶北 DBN\n" +
            "都匀东 KJW\n" +
            "大余 DYG\n" +
            "定州东 DOP\n" +
            "峨眉山 IXW\n" +
            "鄂州东 EFN\n" +
            "防城港北 FBZ\n" +
            "富川 FDZ\n" +
            "丰都 FUW\n" +
            "涪陵北 FEW\n" +
            "抚远 FYB\n" +
            "抚州东 FDG\n" +
            "抚州 FZG\n" +
            "高安 GCG\n" +
            "广安南 VUW\n" +
            "高碑店东 GMP\n" +
            "恭城 GCZ\n" +
            "贵定北 FMW\n" +
            "葛店南 GNN\n" +
            "贵定县 KIW\n" +
            "广汉北 GVW\n" +
            "革居 GEM\n" +
            "光明城 IMQ\n" +
            "广宁 FBQ\n" +
            "桂平 GAZ\n" +
            "弓棚子 GPT\n" +
            "古田北 GBS\n" +
            "广通北 GPM\n" +
            "高台南 GAJ\n" +
            "贵阳北 KQW\n" +
            "高邑西 GNP\n" +
            "惠安 HNS\n" +
            "鹤壁东 HFF\n" +
            "寒葱沟 HKB\n" +
            "邯郸东 HPP\n" +
            "惠东 KDQ\n" +
            "海东西 HDO\n" +
            "洪洞西 HTV\n" +
            "合肥北城 COH\n" +
            "合肥南 ENH\n" +
            "黄冈 KGN\n" +
            "黄冈东 KAN\n" +
            "横沟桥东 HNN\n" +
            "黄冈西 KXN\n" +
            "洪河 HPB\n" +
            "怀化南 KAQ\n" +
            "黄河景区 HCF\n" +
            "花湖 KHN\n" +
            "怀集 FAQ\n" +
            "河口北 HBM\n" +
            "鲘门 KMQ\n" +
            "虎门 IUQ\n" +
            "侯马西 HPV\n" +
            "衡南 HNG\n" +
            "淮南东 HOH\n" +
            "合浦 HVZ\n" +
            "霍邱 FBH\n" +
            "怀仁东 HFV\n" +
            "华容东 HPN\n" +
            "华容南 KRN\n" +
            "黄石北 KSN\n" +
            "黄山北 NYH\n" +
            "贺胜桥东 HLN\n" +
            "和硕 VUR\n" +
            "花山南 KNN\n" +
            "海阳北 HEK\n" +
            "霍州东 HWV\n" +
            "惠州南 KNQ\n" +
            "泾川 JAJ\n" +
            "旌德 NSH\n" +
            "军粮城北 JMP\n" +
            "将乐 JLS\n" +
            "贾鲁河 JLF\n" +
            "即墨北 JVK\n" +
            "建宁县北 JCS\n" +
            "江宁 JJH\n" +
            "建瓯西 JUS\n" +
            "酒泉南 JNJ\n" +
            "句容西 JWH\n" +
            "建水 JSM\n" +
            "界首市 JUN\n" +
            "绩溪北 NRH\n" +
            "介休东 JDV\n" +
            "泾县 LOH\n" +
            "进贤南 JXG\n" +
            "嘉峪关南 JBJ\n" +
            "晋中 JZV\n" +
            "凯里南 QKW\n" +
            "库伦 KLD\n" +
            "葵潭 KTQ\n" +
            "开阳 KVW\n" +
            "来宾北 UCZ\n" +
            "灵璧 GMH\n" +
            "绿博园 LCF\n" +
            "罗城 VCZ\n" +
            "乐都南 LVO\n" +
            "娄底南 UOQ\n" +
            "离堆公园 INW\n" +
            "陆丰 LLQ\n" +
            "禄丰南 LQM\n" +
            "临汾西 LXV\n" +
            "滦河 UDP\n" +
            "漯河西 LBN\n" +
            "罗江东 IKW\n" +
            "龙里北 KFW\n" +
            "醴陵东 UKQ\n" +
            "礼泉 LGY\n" +
            "灵石东 UDV\n" +
            "乐山 IVW\n" +
            "龙市 LAG\n" +
            "溧水 LDH\n" +
            "莱西北 LBK\n" +
            "溧阳 LEH\n" +
            "柳园南 LNR\n" +
            "鹿寨北 LSZ\n" +
            "临泽南 LDJ\n" +
            "明港东 MDN\n" +
            "民和南 MNO\n" +
            "马兰 MLR\n" +
            "民乐 MBJ\n" +
            "玛纳斯 MSR\n" +
            "牟平 MBK\n" +
            "闽清北 MBS\n" +
            "眉山东 IUW\n" +
            "庙山 MSN\n" +
            "门源 MYO\n" +
            "蒙自北 MBM\n" +
            "蒙自 MZM\n" +
            "南城 NDG\n" +
            "南昌西 NXG\n" +
            "南丰 NFG\n" +
            "南湖东 NDN\n" +
            "南江 FIW\n" +
            "南江口 NDQ\n" +
            "南陵 LLH\n" +
            "尼木 NMO\n" +
            "南宁东 NFZ\n" +
            "南平北 NBS\n" +
            "南雄 NCQ\n" +
            "南阳寨 NYF\n" +
            "普安 PAN\n" +
            "屏边 PBM\n" +
            "普定 PGW\n" +
            "平度 PAK\n" +
            "普宁 PEQ\n" +
            "平南南 PAZ\n" +
            "彭山北 PPW\n" +
            "萍乡北 PBG\n" +
            "平遥古城 PDV\n" +
            "彭州 PMW\n" +
            "青白江东 QFW\n" +
            "青岛北 QHK\n" +
            "祁东 QMQ\n" +
            "前锋 QFB\n" +
            "青莲 QEW\n" +
            "清水北 QEJ\n" +
            "青神 QVW\n" +
            "岐山 QAY\n" +
            "庆盛 QSQ\n" +
            "曲水县 QSO\n" +
            "祁县东 QGV\n" +
            "乾县 QBY\n" +
            "祁阳 QWQ\n" +
            "全州南 QNZ\n" +
            "仁布 RUO\n" +
            "荣成 RCK\n" +
            "如东 RIH\n" +
            "榕江 RVW\n" +
            "日喀则 RKO\n" +
            "饶平 RVQ\n" +
            "宋城路 SFF\n" +
            "三都县 KKW\n" +
            "泗洪 GQH\n" +
            "三江南 SWZ\n" +
            "三井子 OJT\n" +
            "双流机场 IPW\n" +
            "双流西 IQW\n" +
            "三明北 SHS\n" +
            "山坡东 SBN\n" +
            "沈丘 SQN\n" +
            "鄯善北 SMR\n" +
            "三水南 RNQ\n" +
            "韶山南 INQ\n" +
            "三穗 QHW\n" +
            "汕尾 OGQ\n" +
            "歙县北 NPH\n" +
            "绍兴北 SLH\n" +
            "始兴 IPQ\n" +
            "泗县 GPH\n" +
            "泗阳 MPH\n" +
            "邵阳北 OVQ\n" +
            "上虞北 SSH\n" +
            "松原北 OCT\n" +
            "山阴 SNV\n" +
            "深圳北 IOQ\n" +
            "神州 SRQ\n" +
            "深圳坪山 IFQ\n" +
            "石嘴山 QQJ\n" +
            "石柱县 OSW\n" +
            "桃村北 TOK\n" +
            "土地堂东 TTN\n" +
            "太谷西 TIV\n" +
            "吐哈 THR\n" +
            "通海 TAM\n" +
            "通化县 TXL\n" +
            "吐鲁番北 TAR\n" +
            "铜陵北 KXH\n" +
            "泰宁 TNS\n" +
            "铜仁南 TNW\n" +
            "汤逊湖 THN\n" +
            "藤县 TAZ\n" +
            "太原南 TNV\n" +
            "文登东 WGK\n" +
            "五府山 WFG\n" +
            "威海北 WHK\n" +
            "乌龙泉南 WFN\n" +
            "五女山 WET\n" +
            "无为 IIH\n" +
            "瓦屋山 WAH\n" +
            "闻喜西 WOV\n" +
            "武夷山北 WBS\n" +
            "武夷山东 WCS\n" +
            "婺源 WYG\n" +
            "武陟 WIF\n" +
            "梧州南 WBZ\n" +
            "兴安北 XDZ\n" +
            "许昌东 XVF\n" +
            "项城 ERN\n" +
            "新都东 EWW\n" +
            "西丰 XFT\n" +
            "襄汾西 XTV\n" +
            "孝感北 XJN\n" +
            "新化南 EJQ\n" +
            "新晃西 EWQ\n" +
            "新津 IRW\n" +
            "新津南 ITW\n" +
            "咸宁东 XKN\n" +
            "咸宁南 UNN\n" +
            "溆浦南 EMQ\n" +
            "协荣 ROO\n" +
            "湘潭北 EDQ\n" +
            "邢台东 EDP\n" +
            "修武西 EXF\n" +
            "新乡东 EGF\n" +
            "新余北 XBG\n" +
            "西阳村 XQF\n" +
            "信阳东 OYN\n" +
            "咸阳秦都 XOY\n" +
            "仙游 XWS\n" +
            "迎宾路 YFW\n" +
            "运城北 ABV\n" +
            "宜春 YEG\n" +
            "岳池 AWW\n" +
            "云浮东 IXQ\n" +
            "永福南 YBZ\n" +
            "雨格 VTM\n" +
            "洋河 GTH\n" +
            "永济北 AJV\n" +
            "运粮河 YEF\n" +
            "炎陵 YAG\n" +
            "杨陵南 YEY\n" +
            "郁南 YKQ\n" +
            "永寿 ASY\n" +
            "玉山南 YGG\n" +
            "永泰 YTS\n" +
            "鹰潭北 YKG\n" +
            "烟台南 YLK\n" +
            "尤溪 YXS\n" +
            "云霄 YBS\n" +
            "宜兴 YUH\n" +
            "应县 YZV\n" +
            "攸县南 YXG\n" +
            "余姚北 CTH\n" +
            "诏安 ZDS\n" +
            "正定机场 ZHP\n" +
            "纸坊东 ZMN\n" +
            "昭化 ZHW\n" +
            "芷江 ZPQ\n" +
            "织金 IZW\n" +
            "左岭 ZSN\n" +
            "驻马店西 ZLN\n" +
            "漳浦 ZCS\n" +
            "肇庆东 FCQ\n" +
            "庄桥 ZQH\n" +
            "钟山西 ZAZ\n" +
            "张掖西 ZEJ\n" +
            "涿州东 ZAP\n" +
            "卓资东 ZDC\n" +
            "郑州东 ZAF\n";
    private static Map<String, String> map = new HashMap<>();
private  static  Map<String,String> map_getname=new HashMap<>();
    private Station_Util() {
    }

    public static Map<String, String> getMap_getname() {
        return map_getname;
    }

    private static Station_Util util = new Station_Util();

    public static Station_Util getIntaces() {
        util.Station_Util_initData();
        return util;
    }

    public static Map<String, String> getMap() {
        return map;
    }

    public void Station_Util_initData() {

        String[] split = station.split("\n");
        List<String> list = Arrays.asList(split);
        for (int i = 0; i < list.size(); i++) {
            String[] split1 = list.get(i).split("\\s");
            CityBean cityBean = new CityBean(split1[1], split1[0]);
            map.put(cityBean.getCityName(), cityBean.getCitycode());
            map_getname.put( cityBean.getCitycode(),cityBean.getCityName());

        }

        System.out.println();
    }

}


